version: '3.1'

services:
    app:
        build: .
        env_file:
            - ./app.env
        ports:
            - 80:3000
        depends_on:
            - db
    db:
        image: mongo:latest
        ports:
            - 27020:27017
        volumes:
            - ./database:/data/db
        env_file:
            - ./db.env
